@base = http://localhost:8080/v1/api
@contentType = application/json;charset=UTF-8

@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvbWFyMDkwNyIsImV4cCI6MTc3NDY1NjMwMCwiaWF0IjoxNzc0NTY5OTAwLCJ1c2VyTmFtZSI6Im9tYXIwOTA3IiwiaWQiOjMsIm5hbWUiOiJPbWFyIiwicm9sZSI6IkFETUlOIiwiY29tcGFueSI6IlBoYXJtYWN5In0.2ZX6Sa2K68YTDLpFZ11RUowfW76fjc2LqoNMEjqje3E

##### Get Role Permission by ID
GET {{base}}/role_permissions/1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

##### Delete Role Permission by ID
DELETE {{base}}/role_permissions/1/2
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

