@base = http://localhost:8080/v1/api
@contentType = application/json;charset=UTF-8

@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvbWFyMDkwNyIsImV4cCI6MTc3NTU3OTkyNywiaWF0IjoxNzc1NDkzNTI3LCJ1c2VyTmFtZSI6Im9tYXIwOTA3IiwiaWQiOjIsIm5hbWUiOiJPbWFyIEdhcmNpYSIsInJvbGUiOiJBRE1JTiIsImNvbXBhbnkiOiJQaGFybWFjeSJ9.dmeKHx_nM0t-H54fsIOeNje74hRLDBi88QZU7HniSxxnYm2zTapZLl__pd96ZpGgudcEnsAsnOdFvO8QKm9t0W5ub-92jUEkHI5KiAv78aD_niZhrtW9HjLkXELp9Jblv6hDSwe7mf9WOSdlmcrufEYMFbhyrUCjFOM9OnHVZKNUegohu1yvSAqXJPzWMEtEswZthRDLCk5JO4kIGR2hdmM0vcyc3Qb0WTEWU7ftKRVJROfKTVTIzOP40C56Lj7YGL8_g5GO2ce7BFx1yMKxB5JjdP2xG8OaGgJ6Cbltr3uM2G7xchEs-aYQD96_InbEdbFn6v3w_PTtl0XR7ObKlg


###LOGIN
POST {{base}}/auth/login
Content-Type: application/json;charset=UTF-8

{
	"username": "omar0907",
	"password": "omar0907"
}

###LOGIN
POST {{base}}/auth/login
Content-Type: application/json;charset=UTF-8

{
	"username": "noemi0907",
	"password": "noemi0907"
}

### Get all permission
PUT {{base}}/permission
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "SALES_MANAGER",
	"description": "Permite gestionar las ventas y los clientes"
}

### Get BY ID	
GET  {{base}}/permission/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get BY NAME
GET  {{base}}/permission/name?page=1&limit=10&total=0&name=SALES_MANAGER
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get BY ID	
GET  {{base}}/permission?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get BY ID	
PATCH   {{base}}/permission/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "INVENTORY_MANAGER",
	"description": "Permite gestionar el inventario y los productos"
}
### Get BY ID	
DELETE  {{base}}/permission/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

###################################ROLE###################################

### Create role
PUT {{base}}/role
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 4,
    "name": "CLIENT",
    "description": "Permite gestionar las compras y el perfil del cliente",
    "createdAt": "2026-04-02T10:33:00Z"
}

### Get BY ID
GET  {{base}}/role/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get BY NAME
GET  {{base}}/role/name?page=1&limit=10&total=0&name=MANAGER
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8	

### Get All ROLE
GET  {{base}}/role?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update ROLE
PATCH   {{base}}/role/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "ADMIN",
	"description": "Permite gestionar el sistema y los usuarios",
	"createdAt": "2026-04-02T10:33:00Z"
}

### Delete ROLE
DELETE  {{base}}/role/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8


##########################USER##########################
### Create USER
PUT {{base}}/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
    "username": "noemi0907",
    "passwordHash": "noemi0907",
    "fullName": "Noemi Bautista",
    "email": "noemi.bautista@example.com",
    "phone": "1234567890",
    "status": "ACTIVE",
    "createdAt": "2026-04-02T10:33:00Z",
    "createdBy": 1,
    "updatedAt": "2026-04-02T10:33:00Z",
    "updatedBy": 1,
    "deletedAt": null
}

### Get BY ID
GET  {{base}}/user/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

###Get ALL USER
GET  {{base}}/user?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8	


### Get BY USERNAME
GET  {{base}}/user/username?page=1&limit=10&total=0&username=noemi0907
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update USER
PATCH   {{base}}/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 4,
    "username": "omar1234",
    "passwordHash": "hashed_password",
    "fullName": "Omar Perez",
    "email": "john.1e@example.com",
    "phone": "1234567890",
    "status": "ACTIVE",
    "createdAt": "2026-04-02T10:33:00Z",
    "createdBy": 1,
    "updatedAt": "2026-04-02T10:33:00Z",
    "updatedBy": 2,
    "deletedAt": "2026-04-02T10:33:00Z"
}

### Delete USER
DELETE  {{base}}/user?username=omar1234&updatedBy=2&status=DELETED
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8


### Update USER STATUS
PUT  {{base}}/user/status?username=john_doe&updatedBy=2&status=INACTIVE
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

##############ROLE-PERMISSION##########################
### Assign Permission to Role
PUT {{base}}/role_permissions
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"roleId": 1,
	"permissionId": 2
}
### Get Permissions by Role ID
GET  {{base}}/role_permissions/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### GET ALL ROLE-PERMISSION
GET  {{base}}/role_permissions/list?page=1&limit=10&total=0&roleId=1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update ROLE-PERMISSION
PATCH   {{base}}/role_permissions/1/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"roleId": 1,
	"permissionId": 2
}

### Delete ROLE-PERMISSION
DELETE  {{base}}/role_permissions/1/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

############USER-ROLE##########################
### Assign Role to User
PUT {{base}}/user_role
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"userId": 5,
	"roleId": 2
}
### Get Roles by User ID
GET  {{base}}/user_role/2/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### GET ALL USER-ROLE
GET  {{base}}/user_role?page=1&limit=10&total=0&userId=2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update USER-ROLE
PATCH   {{base}}/user_role/2/2
Authorization: Bearer {{accessToken}}	
Content-Type: application/json;charset=UTF-8

{
	"userId": 2,
	"roleId": 1
}

### Delete USER-ROLE
DELETE  {{base}}/user_role/2/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#######PAYMENT METHODS##########################
### Create Payment Method
PUT {{base}}/payment_methods
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Cambio",
	"methodType": "CASH",
	"active": true
}

#### GEt BY ID
GET  {{base}}/payment_methods/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8


### Get All Payment Methods
GET  {{base}}/payment_methods?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update Payment Method
PATCH   {{base}}/payment_methods/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 5,
	"name": "Tarjeta de Crédito",
	"methodType": "CREDIT_CARD",
	"active": true
}

### Delete Payment Method
DELETE  {{base}}/payment_methods/7
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

###### INVENTORY-LOCATIONS##########################

### Create Inventory Location
PUT {{base}}/inventory_locations
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Tienda Secundaria",
	"type": "STORE",
	"description": "Tienda secundaria"
}

### Get Inventory Location by ID
GET  {{base}}/inventory_locations/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8\

### Get All Inventory Locations
GET  {{base}}/inventory_locations?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update Inventory Location
PATCH   {{base}}/inventory_locations/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 2,
	"name": "Tienda Principal",
	"type": "STORE",
	"description": "Tienda principal actualizada"
}

### Delete Inventory Location
DELETE  {{base}}/inventory_locations/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#######UNITS##########################
### Create Unit
PUT {{base}}/units
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"code": "Mil",
	"name": "Milliliter",
	"precision": 4
}

### Get Unit by ID
GET  {{base}}/units/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get All Units
GET  {{base}}/units?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Unit
PATCH   {{base}}/units/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 3,
	"code": "L",
	"name": "Liter",
	"precision": 4
}
### Delete Unit
DELETE  {{base}}/units/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

##### TAX PROFILES##########################
### Create Tax Profile
PUT {{base}}/tax_profiles
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "IVA 5%",
	"rate": 0.05,
	"isInclusive": true,
	"description": "Impuesto para IVA al 5%"
}

### Get Tax Profile by ID
GET  {{base}}/tax_profiles/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Tax Profiles
GET  {{base}}/tax_profiles?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Upgrade: Tax Profile
PATCH   {{base}}/tax_profiles/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 3,
	"name": "IVA 15%",
	"rate": 0.15,
	"isInclusive": false,
	"description": "Impuesto para IVA al 15%"
}

### Delete Tax Profile
DELETE  {{base}}/tax_profiles/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

########CATEGORIES##########################
### Create Category
PUT {{base}}/category
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Analgesicos",
	"description": "Categoría para analgésicos"
}
### Get Category by ID
GET  {{base}}/category/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get All Categories
GET  {{base}}/category?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update Category
PATCH {{base}}/category/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 2,
	"name": "Antibióticos",
	"description": "Categoría para antibióticos actualizada",
	"parentId": 1
}
### Delete Category
DELETE  {{base}}/category/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#### SUPPLIERS##########################
### Create Supplier
PUT {{base}}/supplier
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
    
	"id":1,
    "name": "Proveedor B",
    "taxId": "7721248765",
    "contactPerson": "Omar Garcia Godinez",
    "phone": "7721248765",
    "email": "omar.garcia@example.com",
    "address": "Calle Falsa 123",
    "notes": "Proveedor confiable",
    "createdAt": "2024-06-01T12:00:00Z"
}

### Get Supplier by ID
GET  {{base}}/supplier/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Suppliers
GET  {{base}}/supplier?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Supplier
PATCH {{base}}/supplier/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id":1,
	"name": "Proveedor A",
	"taxId": "123456789",
	"contactPerson": "Juan Perez Gomez",
	"phone": "7721248765",
	"email": "juan.perez@example.com",
	"address": "Calle Falsa 123",
	"notes": "Proveedor confiable",
	"createdAt": "2024-06-01T12:00:00Z"
}
### Delete Supplier
DELETE  {{base}}/supplier/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#####CUSTOMERS##########################
### Create Customer
PUT {{base}}/customer
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Cliente A",
	"documentId": "123456789",
	"phone": "7721234567",
	"email": "maria.lopez@example.com",
	"billingAddress": "Avenida Siempre Viva 456",
	"creditLimit": 10000.00,
	"termsDays": 30,
	"status": "ACTIVE",
	"createdAt": "2024-06-01T12:00:00Z"

}

### Get Customer by ID
GET  {{base}}/customer/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Customers
GET  {{base}}/customer?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Customer
PATCH {{base}}/customer/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Cliente A",
	"documentId": "123456789",
	"phone": "7721234567",
	"email": "maria.lopez@example.com",
	"billingAddress": "Avenida Siempre Viva 456",
	"creditLimit": 250000.00,
	"termsDays": 45,
	"status": "ACTIVE",
	"createdAt": "2024-06-01T12:00:00Z"
}
### Delete Customer
DELETE  {{base}}/customer/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#####PRODUCTS##########################
### Create Product
PUT {{base}}/product
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
    "id": 1,
    "sku": "SKU128",
    "name": "Ibuprofeno 750mg",
    "description": "Analgésico",
    "brand": "Marca B",
    "categoryId": 1,
    "unitId": 1,
    "isSellable": true,
    "trackBatches": false,
    "taxProfileId": 1,
    "defaultCost": 150.00,
    "purchasePrice": 170.00,
    "wholesalePrice": 155.00,
    "salePrice": 250.00,
    "defaultPrice": 250.00,
    "createdAt": "2024-06-01T12:00:00Z",
    "updatedAt": null,
    "deletedAt": null
}

### Get Product by ID
GET  {{base}}/product/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Products
GET  {{base}}/product?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Product
PATCH {{base}}/product/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"sku": "SKU128",
	"name": "Ibuprofeno 750mg",
	"description": "Analgésico",
	"brand": "Marca B",
	"categoryId": 1,
	"unitId": 1,
	"isSellable": true,
	"trackBatches": false,
	"taxProfileId": 1,
	"defaultCost": 110.00,
	"purchasePrice": 130.00,
	"wholesalePrice": 160.00,
	"salePrice": 210.00,
	"defaultPrice": 260.00,
	"createdAt": "2024-06-01T12:00:00Z",
	"updatedAt": "2024-06-02T12:00:00Z",
	"deletedAt": null
}
####### Delete Product
DELETE  {{base}}/product/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

######### PRODUCT_BARCODES##########################
### Create Product Barcode
PUT {{base}}/product_barcode
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"productId": 1,
	"barcode": "1234567890123",
	"barcodeType": "EAN-13",
	"createdAt": "2024-06-01T12:00:00Z"
}
### Get Product Barcode by ID
GET  {{base}}/product_barcode/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Product Barcodes
GET  {{base}}/product_barcode?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Product Barcode
PATCH {{base}}/product_barcode/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"productId": 1,
	"barcode": "9876543210987",
	"barcodeType": "EAN-13",
	"createdAt": "2024-06-01T12:00:00Z"
}

### Get Product Barcode by Barcode
GET  {{base}}/product_barcode/barcode?barcode=9876543210987&page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Delete Product Barcode
DELETE  {{base}}/product_barcode/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

##### PRODUCT_PRICES##########################
### Create Product Price
PUT {{base}}/product_price
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"productId": 1,
	"priceType": "SALE",
	"price": 250.00,
	"startsAt": "2024-06-01T12:00:00Z",
	"endsAt": null,
	"createdAt": "2024-06-01T12:00:00Z"
}
### Get Product Price by ID
GET  {{base}}/product_price/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Product Prices
GET  {{base}}/product_price?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Product Price
PATCH {{base}}/product_price/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"productId": 1,
	"priceType": "RETAIL",
	"price": 25.00,
	"startsAt": "2024-06-01T12:00:00Z",
	"endsAt": null,
	"createdAt": "2024-06-01T12:00:00Z"
}
###### Delete Product Price	
DELETE  {{base}}/product_price/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

##### purchases ##########################
### Create Purchase
PUT {{base}}/purchase
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
    "id": 1,
    "supplierId": 2,
    "invoiceNo": "INV-001",
    "date": "2024-06-01T12:00:00Z",
    "subtotal": 200.00,
    "taxTotal": 100.00,
    "total": 300.00,
    "status": "PENDING",
    "createdAt": "2024-06-01T12:00:00Z",
    "createdBy": 2
}
### Get Purchase by ID
GET  {{base}}/purchase/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Purchases
GET  {{base}}/purchase?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Purchase
PATCH {{base}}/purchase/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 3,
	"supplierId": 2,
	"invoiceNo": "INV-001",
	"date": "2024-06-01T12:00:00Z",
	"subtotal": 200.00,
	"taxTotal": 100.00,
	"total": 300.00,
	"status": "COMPLETED",
	"createdAt": "2024-06-01T12:00:00Z",
	"createdBy": 2
}

########## Delete Purchase
DELETE  {{base}}/purchase/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8


##### product_lots ##########################
### Create Product Lot
PUT {{base}}/product_lot
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"productId": 1,
	"lotNumber": "LOT-001",
	"purchaseId": 2,
	"expiryDate": "2024-06-01",
	"qtyOnHand": 100.00,
	"createdAt": "2024-06-01T12:00:00Z"
}

### Get Product Lot by ID
GET  {{base}}/product_lot/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Product Lots
GET  {{base}}/product_lot?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Product Lot

PATCH {{base}}/product_lot/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8	

{
	"id": 2,
	"productId": 1,
	"lotNumber": "LOT-001",
	"purchaseId": 2,
	"expiryDate": "2024-06-01",
	"qtyOnHand": 100.00,
	"createdAt": "2024-06-01T12:00:00Z"
}

#### PUSHASE ITEMS ##########################
### Create Purchase Item
PUT {{base}}/purchase_item
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"purchaseId": 2,
	"productId": 1,
	"lotId": 2,
	"qty": 10.00,
	"unitCost": 150.00,
	"discount": 0.00,
	"taxAmount": 75.00,
	"lineTotal": 1500.00
}
### Get Purchase Item by ID
GET  {{base}}/purchase_item/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get All Purchase Items
GET  {{base}}/purchase_item?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update Purchase Item
PATCH {{base}}/purchase_item/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"purchaseId": 2,
	"productId": 1,
	"lotId": 2,
	"qty": 5.00,
	"unitCost": 20.00,
	"discount": 0.00,
	"taxAmount": 25.00,
	"lineTotal": 2000.00
}
#########purchase_payments########33##########################
### Create Purchase Payment
PUT {{base}}/purchase_payment
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"purchaseId": 2,
	"methodId": 6,
	"amount": 300.00,
	"paidAt": "2024-06-01T12:00:00Z",
	"reference": "Pago inicial"
}
### Get Purchase Payment by ID
GET  {{base}}/purchase_payment/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Purchase Payments
GET  {{base}}/purchase_payment?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Purchase Payment
PATCH {{base}}/purchase_payment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"purchaseId": 2,
	"methodId": 6,
	"amount": 300.00,
	"paidAt": "2024-06-01T12:00:00Z",
	"reference": "Pago inicial"
}
### Delete Purchase Payment
DELETE  {{base}}/purchase_payment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

############SALES##########################
### Create Sale
PUT {{base}}/sale
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"customerId": 1,
	"userId": 2,
	"invoiceNo": "INV-001",
	"date": "2024-06-01T12:00:00Z",
	"subtotal": 200.00,
	"taxTotal": 100.00,
	"discountTotal": 0.00,
	"total": 300.00,
	"status": "PENDING",
	"isCredit": false,
	"createdAt": "2024-06-01T12:00:00Z"
}
### Get Sale by ID
GET  {{base}}/sale/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Sales
GET  {{base}}/sale?page=1&limit=10&total=0&dateInit=2026-04-04&dateEnd=2026-04-05
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Sale
PATCH {{base}}/sale/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"customerId": 1,
	"userId": 2,
	"invoiceNo": "INV-001",
	"date": "2024-06-01T12:00:00Z",
	"subtotal": 200.00,
	"taxTotal": 100.00,
	"discountTotal": 0.00,
	"total": 300.00,
	"status": "COMPLETED",
	"isCredit": false,
	"createdAt": "2024-06-01T12:00:00Z"
}
### Delete Sale
DELETE  {{base}}/sale/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#######SALE ITEMS##########################
### Create Sale Item
PUT {{base}}/sale_item
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"saleId": 2,
	"productId": 1,
	"lotId": 2,
	"qty": 2.00,
	"unitPrice": 15.00,
	"discount": 0.00,
	"taxAmount": 15.00,
	"lineTotal": 30.00
}
### Get Sale Item by ID
GET  {{base}}/sale_item/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Get All Sale Items
GET  {{base}}/sale_item?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#####sale_payments##########################
### Create Sale Payment
PUT {{base}}/sale_payment
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"saleId": 2,
	"methodId": 6,
	"amount": 30.00,
	"paidAt": "2024-06-01T12:00:00Z",
	"reference": "Pago inicial"
}

### Get Sale Payment by ID
GET  {{base}}/sale_payment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Sale Payments
GET  {{base}}/sale_payment?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Sale Payment
PATCH {{base}}/sale_payment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"saleId": 2,
	"methodId": 6,
	"amount": 30.00,
	"paidAt": "2024-06-01T12:00:00Z",
	"reference": "Pago inicial"
}
### Delete Sale Payment
DELETE  {{base}}/sale_payment/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#####CUSTOMER_CREDIT_ACCOUNT##########################
### Create Customer Credit Account
PUT {{base}}/customer_credit_account
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"customerId": 1,
	"balance": 1000.00,
	"limitAmount": 5000.00,
	"lastOverdueDate": "2024-06-01"
}

### Get Customer Credit Account by ID
GET  {{base}}/customer_credit_account/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Customer Credit Accounts
GET  {{base}}/customer_credit_account?page=1&limit=10&total=0&customerId=1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Customer Credit Account
PATCH {{base}}/customer_credit_account/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
{
	"id": 1,
	"customerId": 1,
	"balance": 1500.00,
	"limitAmount": 5000.00,
	"lastOverdueDate": "2024-06-01"
}
### Delete Customer Credit Account
DELETE  {{base}}/customer_credit_account/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#########DISCOUNTS##########################
### Create Discount
PUT {{base}}/discount
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
    "code": "DISCOUNT2024",
    "name": "Summer Sale",
    "description": "Discount for summer season",
    "discountType": "percentage",
    "value": 10.0,
	"appliesTo": "product",
    "productId": 1,
    "categoryId": 1,
    "customerId": 1,
    "minQty": 1.0,
    "maxUses": 10,
    "priority": 1,
    "startAt": "2024-06-01T12:00:00Z",
    "endAt": "2024-06-30T12:00:00Z",
    "active": true,
    "createdAt": "2024-06-01T12:00:00Z",
    "createdBy": 2
}
### Get Discount by ID
GET  {{base}}/discount/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Discounts
GET  {{base}}/discount?page=1&limit=10&total=0&name=Summer%20Sale&productId=1&categoryId=1&customerId=1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Discount
PATCH {{base}}/discount/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"code": "DISCOUNT2024",
	"name": "Summer Sale",
	"description": "Discount for summer season",
	"discountType": "percentage",
	"value": 15.0,
	"appliesTo": "product",
	"productId": 1,
	"categoryId": 1,
	"customerId": 1,
	"minQty": 1.0,
	"maxUses": 10,
	"priority": 1,
	"startAt": "2024-06-01T12:00:00Z",
	"endAt": "2024-06-30T12:00:00Z",
	"active": true,
	"createdAt": "2024-06-01T12:00:00Z",
	"createdBy": 2
}

### Delete Discount
DELETE  {{base}}/discount/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

########INVENTORY_MOVEMENT##########################
### Create Inventory Movement
PUT {{base}}/inventory_movement
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
    "productId": 1,
    "lotId": 2,
    "locationId": 1,
    "changeQty": 10.0,
    "reason": "Stock adjustment",
    "referenceType": "some_reference_type",
    "referenceId": 1,
    "cost": 100.0,
    "createdAt": "2024-06-01T12:00:00Z",
    "createdBy": 2
}
### Get Inventory Movement by ID
GET  {{base}}/inventory_movement/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Inventory Movements
GET  {{base}}/inventory_movement?page=1&limit=10&total=0&productId=1&locationId=1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update Inventory Movement
PATCH {{base}}/inventory_movement/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"productId": 1,
	"lotId": 2,
	"locationId": 1,
	"changeQty": 15.0,
	"reason": "Stock adjustment",
	"referenceType": "some_reference_type",
	"referenceId": 1,
	"cost": 100.0,
	"createdAt": "2024-06-01T12:00:00Z",
	"createdBy": 2
}
### Delete Inventory Movement
DELETE  {{base}}/inventory_movement
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

##############cash_journals##########################
### Create Cash Journal
PUT {{base}}/cash_journal
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
    "id": 1,
    "name": "Cash Journal 1",
    "description": "Description of Cash Journal 1",
    "openingAmount": 1000.0,
    "openedAt": "2024-06-01T12:00:00Z",
    "closedAt": null,
    "openedBy": 2,
    "closedBy": null,
    "status": "OPEN",
    "createdAt": "2024-06-01T12:00:00Z"
}

### Get Cash Journal by ID
GET  {{base}}/cash_journal/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Cash Journals
GET  {{base}}/cash_journal?page=1&limit=10&total=0&status=OPEN
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

### Update Cash Journal
PATCH {{base}}/cash_journal/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Cash Journal 1",
	"description": "Description of Cash Journal 1",
	"openingAmount": 1000.0,
	"openedAt": "2024-06-01T12:00:00Z",
	"closedAt": null,
	"openedBy": 2,
	"closedBy": null,
	"status": "CLOSED",
	"createdAt": "2024-06-01T12:00:00Z"
}
### Delete Cash Journal
DELETE  {{base}}/cash_journal/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

#########cash_entries##########################
### Create Cash Entry
PUT {{base}}/cash_entry
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
    "name": "Cash Entry 1",
    "entryType": "other",
    "amount": 100.0,
    "methodId": 6,
    "relatedType": "SALE",
    "relatedId": 1,
    "description": "Description of Cash Entry 1",
    "recordedAt": "2024-06-01T12:00:00Z",
    "recordedBy": 2
}

### Get Cash Entry by ID
GET  {{base}}/cash_entry/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Get All Cash Entries
GET  {{base}}/cash_entry?page=1&limit=10&total=0&entryType=other
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
### Update Cash Entry
PATCH {{base}}/cash_entry/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

{
	"id": 1,
	"name": "Cash Entry 1",
	"entryType": "other",
	"amount": 150.0,
	"methodId": 6,
	"relatedType": "SALE",
	"relatedId": 1,
	"description": "Description of Cash Entry 1",
	"recordedAt": "2024-06-01T12:00:00Z",
	"recordedBy": 2
}
### Delete Cash Entry
DELETE  {{base}}/cash_entry/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8

##########AUDIT_LOGS##########################
### Get All Audit Logs
GET  {{base}}/audit_log?page=1&limit=10&total=0
Authorization: Bearer {{accessToken}}
Content-Type: application/json;charset=UTF-8
