version: '3.9'
services:
  backend:
    image: ${IMAGE_NAME}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "postgres://postgres:admin@host.docker.internal:5432/postgres?options=--search_path=pharmacy"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      PORT: "8081"
      SERVER_ADDR: "0.0.0.0"
      JWT_EXPIRATION: "3600"
      LOG_LEVEL: "off"
      RUST_LOG: "off"
      PASSWORD_SALT: "${PASSWORD_SALT}"
      API_JWT_PRIVATE_PEM_PATH: "./pem/jwt_private.pem"
      API_JWT_PUBLIC_PEM_PATH: "./pem/jwt_public.pem"
      API_JWT_SECRET: "${API_JWT_SECRET}"
      API_JWT_SECRET_REFRESH: "${API_JWT_SECRET_REFRESH}"
      APP_TIMEZONE: "America/Mexico_City"
    volumes:
      - ./pem:/app/pem:ro
