//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "cash_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub entry_type: String,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub amount: Decimal,
    pub method_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub related_type: Option<String>,
    pub related_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub recorded_at: DateTimeWithTimeZone,
    pub recorded_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::MethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::RecordedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
