//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "pharmacy", table_name = "client_orden_payment")]

pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i64,
    pub orden_id: i64,
    pub client_id: i64,
    pub employee_id: i64,
    #[sea_orm(column_type = "Float")]
    pub total_orden: f32,
    pub date_orden: Option<Date>,
    pub time_orden: Option<Time>,
    pub status_orden: bool,
    pub payment_method: Option<String>,
    pub payment_status: Option<String>,
    pub payment_partial: Option<f32>,
    pub payment_date: Option<Date>,
    pub payment_time: Option<Time>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
