//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "client")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub client_id: i64,
    pub client_address: Option<String>,
    pub client_city: Option<String>,
    pub client_country: Option<String>,
    pub client_date: Date,
    pub client_email: Option<String>,
    pub client_last_name: String,
    pub client_name: String,
    pub client_phone: Option<String>,
    pub client_postal_code: Option<String>,
    pub client_state: Option<String>,
    pub client_status: bool,
    pub client_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
