//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "inventory_movements")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub product_id: i64,
    pub lot_id: Option<i64>,
    pub location_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))")]
    pub change_qty: Decimal,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reference_type: Option<String>,
    pub reference_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub cost: Option<Decimal>,
    pub created_at: DateTimeWithTimeZone,
    pub created_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inventory_locations::Entity",
        from = "Column::LocationId",
        to = "super::inventory_locations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    InventoryLocations,
    #[sea_orm(
        belongs_to = "super::product_lots::Entity",
        from = "Column::LotId",
        to = "super::product_lots::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ProductLots,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::inventory_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryLocations.def()
    }
}

impl Related<super::product_lots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductLots.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
