//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod client;
pub mod client_orden;
pub mod product;
pub mod sale;
pub mod saledetal;
pub mod user;
pub mod userjwt;
pub mod userjwtrefresh;
