//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod audit_log;
pub mod cash_entries;
pub mod cash_journals;
pub mod categories;
pub mod commission_parameters;
pub mod config_parameters;
pub mod customer_credit_accounts;
pub mod customers;
pub mod discounts;
pub mod inventory_locations;
pub mod inventory_movements;
pub mod payment_methods;
pub mod permissions;
pub mod product_barcodes;
pub mod product_lots;
pub mod product_prices;
pub mod products;
pub mod purchase_items;
pub mod purchase_payments;
pub mod purchases;
pub mod role_permissions;
pub mod roles;
pub mod sale_items;
pub mod sale_payment_allocations;
pub mod sale_payments;
pub mod sales;
pub mod suppliers;
pub mod tax_profiles;
pub mod tax_rates;
pub mod units;
pub mod user_roles;
pub mod users;
