//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "payment_methods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub method_type: Option<String>,
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cash_entries::Entity")]
    CashEntries,
    #[sea_orm(has_many = "super::purchase_payments::Entity")]
    PurchasePayments,
    #[sea_orm(has_many = "super::sale_payments::Entity")]
    SalePayments,
}

impl Related<super::cash_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CashEntries.def()
    }
}

impl Related<super::purchase_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchasePayments.def()
    }
}

impl Related<super::sale_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePayments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
