//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::client::Entity as Client;
pub use super::client_orden::Entity as ClientOrden;
pub use super::product::Entity as Product;
pub use super::sale::Entity as Sale;
pub use super::saledetal::Entity as Saledetal;
pub use super::user::Entity as User;
pub use super::userjwt::Entity as Userjwt;
pub use super::userjwtrefresh::Entity as Userjwtrefresh;
