//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub sku: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub brand: Option<String>,
    pub category_id: Option<i64>,
    pub unit_id: Option<i64>,
    pub is_sellable: bool,
    pub track_batches: bool,
    pub tax_profile_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub default_cost: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub purchase_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub wholesale_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub sale_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub default_price: Option<Decimal>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Categories,
    #[sea_orm(has_many = "super::discounts::Entity")]
    Discounts,
    #[sea_orm(has_many = "super::inventory_movements::Entity")]
    InventoryMovements,
    #[sea_orm(has_many = "super::product_barcodes::Entity")]
    ProductBarcodes,
    #[sea_orm(has_many = "super::product_lots::Entity")]
    ProductLots,
    #[sea_orm(has_many = "super::product_prices::Entity")]
    ProductPrices,
    #[sea_orm(has_many = "super::purchase_items::Entity")]
    PurchaseItems,
    #[sea_orm(has_many = "super::sale_items::Entity")]
    SaleItems,
    #[sea_orm(
        belongs_to = "super::tax_profiles::Entity",
        from = "Column::TaxProfileId",
        to = "super::tax_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TaxProfiles,
    #[sea_orm(
        belongs_to = "super::units::Entity",
        from = "Column::UnitId",
        to = "super::units::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Units,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discounts.def()
    }
}

impl Related<super::inventory_movements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryMovements.def()
    }
}

impl Related<super::product_barcodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductBarcodes.def()
    }
}

impl Related<super::product_lots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductLots.def()
    }
}

impl Related<super::product_prices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductPrices.def()
    }
}

impl Related<super::purchase_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseItems.def()
    }
}

impl Related<super::sale_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleItems.def()
    }
}

impl Related<super::tax_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxProfiles.def()
    }
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
