//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "product_lots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub product_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub lot_number: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))")]
    pub qty_on_hand: Decimal,
    pub expiry_date: Option<Date>,
    pub purchase_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::inventory_movements::Entity")]
    InventoryMovements,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Products,
    #[sea_orm(has_many = "super::purchase_items::Entity")]
    PurchaseItems,
    #[sea_orm(
        belongs_to = "super::purchases::Entity",
        from = "Column::PurchaseId",
        to = "super::purchases::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Purchases,
    #[sea_orm(has_many = "super::sale_items::Entity")]
    SaleItems,
}

impl Related<super::inventory_movements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryMovements.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::purchase_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseItems.def()
    }
}

impl Related<super::purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchases.def()
    }
}

impl Related<super::sale_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
