//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "pharmacy", table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub product_id: i64,
    pub product_name: String,
    pub product_catalog: i32,
    pub product_count: i32,
    pub product_code_bar: String,
    #[sea_orm(column_type = "Float")]
    pub product_price: f32,
    pub product_desc: Option<String>,
    pub product_lote: Option<String>,
    pub product_date: Option<Date>,
    pub product_lastmdate: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
