//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "purchase_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub purchase_id: i64,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub amount: Decimal,
    pub method_id: Option<i64>,
    pub paid_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub reference: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::MethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::purchases::Entity",
        from = "Column::PurchaseId",
        to = "super::purchases::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Purchases,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
