//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "purchases")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub supplier_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_no: Option<String>,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub subtotal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub tax_total: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub total: Decimal,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub created_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_lots::Entity")]
    ProductLots,
    #[sea_orm(has_many = "super::purchase_items::Entity")]
    PurchaseItems,
    #[sea_orm(has_many = "super::purchase_payments::Entity")]
    PurchasePayments,
    #[sea_orm(
        belongs_to = "super::suppliers::Entity",
        from = "Column::SupplierId",
        to = "super::suppliers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Suppliers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::product_lots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductLots.def()
    }
}

impl Related<super::purchase_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseItems.def()
    }
}

impl Related<super::purchase_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchasePayments.def()
    }
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
