//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "sales")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub customer_id: Option<i64>,
    pub user_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_no: Option<String>,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub subtotal: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub tax_total: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub discount_total: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub total: Decimal,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub is_credit: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Customers,
    #[sea_orm(has_many = "super::sale_items::Entity")]
    SaleItems,
    #[sea_orm(has_many = "super::sale_payment_allocations::Entity")]
    SalePaymentAllocations,
    #[sea_orm(has_many = "super::sale_payments::Entity")]
    SalePayments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::sale_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleItems.def()
    }
}

impl Related<super::sale_payment_allocations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePaymentAllocations.def()
    }
}

impl Related<super::sale_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePayments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
