//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "sale_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sale_id: i64,
    pub product_id: i64,
    pub lot_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))")]
    pub qty: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))")]
    pub unit_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub discount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub tax_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub line_total: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_lots::Entity",
        from = "Column::LotId",
        to = "super::product_lots::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ProductLots,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::sales::Entity",
        from = "Column::SaleId",
        to = "super::sales::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sales,
}

impl Related<super::product_lots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductLots.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
