//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "sale_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sale_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub amount: Decimal,
    pub method_id: Option<i64>,
    pub paid_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub reference: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::MethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PaymentMethods,
    #[sea_orm(has_many = "super::sale_payment_allocations::Entity")]
    SalePaymentAllocations,
    #[sea_orm(
        belongs_to = "super::sales::Entity",
        from = "Column::SaleId",
        to = "super::sales::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sales,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::sale_payment_allocations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePaymentAllocations.def()
    }
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
