//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "pharmacy", table_name = "saledetal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub date_sale: Option<Date>,
    pub product_code_bar: Option<String>,
    pub product_count: Option<i64>,
    pub product_id: i64,
    #[sea_orm(column_type = "Float")]
    pub product_price: f32,
    pub time_sale: Option<Time>,
    pub id_sale: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
