//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "pharmacy", table_name = "sale")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub date_sale: Option<Date>,
    #[sea_orm(column_type = "Float")]
    pub discount: f32,
    pub id_sale_detl: i64,
    #[sea_orm(column_type = "Float")]
    pub iva: f32,
    pub msg: Option<String>,
    pub payment_method: Option<String>,
    pub payment_status: Option<String>,
    pub status: Option<String>,
    #[sea_orm(column_type = "Float")]
    pub sub_total: f32,
    pub time_sale: Option<Time>,
    #[sea_orm(column_type = "Float")]
    pub total: f32,
    pub username: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
