//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "sale_payment_allocations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub payment_id: i64,
    pub credit_invoice_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))")]
    pub amount: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sale_payments::Entity",
        from = "Column::PaymentId",
        to = "super::sale_payments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SalePayments,
    #[sea_orm(
        belongs_to = "super::sales::Entity",
        from = "Column::CreditInvoiceId",
        to = "super::sales::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Sales,
}

impl Related<super::sale_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalePayments.def()
    }
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
