//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "t_accounts_payable")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub purchase_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_no: Option<String>,
    pub supplier_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub supplier_name: Option<String>,
    pub invoice_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub invoice_total: Option<Decimal>,
    pub paid_amount: Option<Decimal>,
    pub outstanding_amount: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
