//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_customer_invoice_aging")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub invoice_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_no: Option<String>,
    pub customer_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub customer_name: Option<String>,
    pub invoice_date: Option<DateTimeWithTimeZone>,
    pub due_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub paid_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub outstanding: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_status: Option<String>,
    pub days_overdue: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
