//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_sale_items_detail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sale_item_id: i64,
    pub sale_id: Option<i64>,
    pub product_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub product_name: Option<String>,
    pub lot_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))", nullable)]
    pub qty: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))", nullable)]
    pub unit_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub discount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub tax_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub line_total: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
