//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_cash_journal_balance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub cash_journal_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub opening_amount: Option<Decimal>,
    pub opened_at: Option<DateTimeWithTimeZone>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub inflow: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub outflow: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub balance: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
