//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_sales_daily_summary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub day: DateTimeWithTimeZone,
    pub sales_count: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub subtotal: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub tax_total: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub discount_total: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub total: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub total_credit: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
