//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_inventory_stock")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub product_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub sku: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub product_name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((14, 4)))", nullable)]
    pub qty_on_hand: Option<Decimal>,
    pub max_expiry_date: Option<Date>,
    pub last_movement_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
