//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_sales_with_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub invoice_no: Option<String>,
    pub date: Option<DateTimeWithTimeZone>,
    pub customer_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub customer_name: Option<String>,
    pub user_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub subtotal: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub tax_total: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub discount_total: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub total: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    pub is_credit: Option<bool>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub paid_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub allocated_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub outstanding: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
