//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "pharmacy", table_name = "vw_t_customer_account_summary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub customer_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub customer_name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub total_invoiced: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub total_paid: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((14, 2)))", nullable)]
    pub balance: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
